name: groq_sdk
description: >-
  A Dart library for seamless Groq Cloud API integration. 
  Easily build AI-powered applications leveraging Groq's cutting-edge language models.
version: 0.1.1
repository: https://github.com/oriventi/groq-dart-sdk

library: groq_sdk.dart

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  http: ^1.2.1

# assets:
#   - res/audio.m4a

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
